require "mruby/source"

# The revision the source tree sits at reaches the build as a generated
# `mruby/revision.h`. `src/version.c` is alone in including it, so the revision
# reaches `MRUBY_DESCRIPTION` and the `MRUBY_REVISION` constant while every
# other object is compiled without it: a commit recompiles one object rather
# than the whole tree, which is what a define on the command line would cost.
#
# `#{build_dir}/include` is already on every compiler's include path, put there
# by `tasks/presym.rake` for the headers it generates.

# The header is written on every build, so that a commit made between two
# builds is not missed, but only where its content actually changed: an
# unchanged header keeps its timestamp, and the object that includes it is left
# alone.
revision_header_content = ->() do
  revision = MRuby::Source::MRUBY_REVISION
  body = if revision.empty?
           "/* The build found no repository to read a revision from. */\n"
         else
           "#define MRUBY_REVISION #{revision.inspect}\n"
         end
  <<~HEADER
    /*
    ** mruby/revision.h - the source revision this build was made from
    **
    ** Generated by `tasks/revision.rake`. Do not edit.
    */

    #ifndef MRUBY_REVISION_H
    #define MRUBY_REVISION_H

    #{body}
    #endif  /* MRUBY_REVISION_H */
  HEADER
end

MRuby.each_target do |build|
  # `src/version.c` is compiled into libmruby, and a build without one has
  # nothing to tell the revision to.
  next unless build.libmruby_enabled?

  header = "#{build.build_dir}/include/mruby/revision.h"

  revision_task = file header do |t|
    content = revision_header_content.()
    next if File.exist?(t.name) && File.binread(t.name) == content
    mkdir_p File.dirname(t.name)
    File.binwrite(t.name, content)
    _pp "GEN", t.name.relative_path
  end

  # A file task with no prerequisites is done as soon as the file exists, and
  # the revision changes with no file of the build's changing. Ask for the task
  # every time, and let it decide whether the header it writes differs from the
  # one on disk.
  revision_task.define_singleton_method(:needed?) { true }

  file build.objfile("#{build.build_dir}/src/version") => header
end
