# Generate the character property table `\p{...}` reads, from the Unicode
# Character Database.
#
#   ruby mrbgems/mruby-regexp/tools/gen_prop.rb mrbgems/mruby-regexp/src [UCDDIR]
#
# UCDDIR holds UnicodeData.txt, Scripts.txt and PropertyValueAliases.txt as
# published under https://www.unicode.org/Public/<version>/ucd/, and defaults
# to the copy tools/unicode/ucd.rb names, the same one the other table
# generators read. The files are not in the repository: they are read when the
# table is regenerated and nowhere else. Which characters each property holds,
# and what it may be called, is tools/unicode/prop_data.rb's to say; this file
# only packs the answer.
#
# re_prop.h holds the general category and the script of every codepoint, and
# every name a property escape may call one of them by. It is compiled only
# into a build that reads its strings as characters and classifies them by
# Unicode, which is the same build that carries the POSIX bracket table.
#
# Both classifications are held as runs: every codepoint has exactly one
# answer, so the codepoint space is cut into runs over which the answer does
# not change, and a run is one 32-bit entry, the codepoint it starts at in the
# high bits and the answer in the low. One binary search answers a run, and the
# runs number a fraction of what the values would take as separate range lists.
#
# A named general category is a mask over the concrete ones rather than one of
# them, so that a group (`\p{L}`) and a single category (`\p{Lu}`) are the same
# question asked once. A script is the value itself, there being no groups of
# scripts to ask about.

require_relative '../../../tools/unicode/prop_data'

outdir = ARGV[0] or abort "usage: #{$0} OUTDIR [UCDDIR]"
data = Unicode::PropData.load(ARGV[1])
version = data.version

MAX_CP = 0x10FFFF
MAX_START = (1 << 21) - 1

# ------------------------------------------------------------------- gather

# How many bits a run's answer takes, and how far the codepoint is shifted up
# past it. Both are as tight as the values allow, so a change in the database
# that adds a script or a category is a change in the header rather than a
# silent overflow; the checks below are what makes it the first.
def bits_for(count)
  bits = 1
  bits += 1 while (1 << bits) < count
  bits
end

gc_bits = bits_for(data.categories.size)
script_bits = bits_for(data.scripts.size)

[[data.gc_runs, gc_bits, 'general category'],
 [data.script_runs, script_bits, 'script']].each do |runs, bits, what|
  abort "#{what}: a run starts past U+10FFFF" if runs.last[0] > MAX_START
  abort "#{what}: #{bits} bits do not leave room for the codepoint" if bits > 32 - 21
  abort "#{what}: the first run does not start at U+0000" unless runs.first[0] == 0
end

# The masks, in the order the names index them: the concrete categories first,
# in the order that is their bit, so that the header reads as the bits it
# names, and the groups after in the order the names give them.
mask_names = data.gc_masks.keys.sort_by { |name| [data.categories.index(name) || data.categories.size, name] }
mask_id = {}
mask_names.each_with_index { |name, i| mask_id[name] = i }
abort "#{mask_names.size} masks do not fit a byte" if mask_names.size > 256
abort "#{data.scripts.size} scripts do not fit a byte" if data.scripts.size > 256

script_id = {}
data.scripts.each_with_index { |name, i| script_id[name] = i }

# The name table, as one blob of characters and an entry naming a slice of it.
# The entries are sorted by name, which is what lets a lookup search them; the
# blob is packed in that order too, so a name that is the head of another still
# gets its own bytes.
blob = +''
entries = data.names.map do |name, kind, value|
  off = blob.index(name) || (blob << name; blob.length - name.length)
  abort "#{name}: does not fit the blob" if off > 0xffff || name.length > 0xff
  id = kind == :gc ? mask_id.fetch(value) : script_id.fetch(value)
  [name, off, kind, value, id]
end

# ------------------------------------------------------------------- emit

def emit_runs(out, name, runs, bits, label)
  out.puts "static const uint32_t #{name}[] = {"
  runs.each do |start, id|
    out.puts "  0x%08X,  /* U+%04X %s */" % [(start << bits) | id, start, label.call(id)]
  end
  out.puts "};"
  out.puts
end

File.open(File.join(outdir, 're_prop.h'), 'w') do |out|
  out.puts <<~HEAD
    /*
    ** re_prop.h - the general category and the script of every codepoint
    **
    ** Generated by mrbgems/mruby-regexp/tools/gen_prop.rb from the Unicode
    ** #{version} character database. Do not edit by hand.
    **
    ** What `\\p{...}` asks about: the one general category a codepoint has,
    ** out of UnicodeData.txt, and the one script Scripts.txt gives it, Unknown
    ** where it gives none. Every codepoint is in the tables, ASCII included:
    ** the compiler reads a property's ASCII off them once, into the class
    ** bitmap, and the matcher reads them for what stands above it.
    **
    ** The binary properties beyond these two are not here; see
    ** tools/unicode/prop_data.rb for what that leaves out and why.
    **
    ** See Copyright Notice in mruby.h
    */

    #ifndef MRB_RE_PROP_H
    #define MRB_RE_PROP_H

    /* One run of codepoints sharing an answer, as a 32-bit entry: the answer
       in the low bits and the codepoint the run starts at above it. Ascending;
       a run ends where the next begins, and the last at U+10FFFF. The first
       starts at U+0000, so every codepoint is inside one. */
    #define RE_PROP_GC_BITS #{gc_bits}
    #define RE_PROP_SCRIPT_BITS #{script_bits}
  HEAD
  out.puts

  out.puts "/* The concrete general categories, each at the bit it has in a mask. */"
  data.categories.each_with_index do |cat, i|
    out.puts "/*   %2d  %s */" % [i, cat]
  end
  out.puts
  emit_runs(out, 're_prop_gc_runs', data.gc_runs, gc_bits,
            ->(id) { data.categories[id] })
  out.puts "#define RE_PROP_GC_RUN_COUNT (sizeof(re_prop_gc_runs) / sizeof(re_prop_gc_runs[0]))"
  out.puts

  emit_runs(out, 're_prop_script_runs', data.script_runs, script_bits,
            ->(id) { data.scripts[id] })
  out.puts "#define RE_PROP_SCRIPT_RUN_COUNT (sizeof(re_prop_script_runs) / sizeof(re_prop_script_runs[0]))"
  out.puts

  out.puts <<~MASKS
    /* What a named general category comes to, as a mask of the categories
       above: a group holds several and a concrete category holds itself. */
    static const uint32_t re_prop_gc_masks[] = {
  MASKS
  mask_names.each do |name|
    out.puts "  0x%08X,  /* %s */" % [data.gc_masks[name], name]
  end
  out.puts "};"
  out.puts

  out.puts <<~NAMES
    /* Every name a property escape may call one of them by, folded the way the
       compiler folds the name it reads: lower case, and without the
       underscores, hyphens and spaces that are not part of a name. Sorted, so
       that a lookup is a search; each entry names a slice of the blob and what
       the name stands for. */
    #define RE_PROP_KIND_GC 0
    #define RE_PROP_KIND_SCRIPT 1

    typedef struct {
      uint16_t off;   /* where the name starts in re_prop_name_chars */
      uint8_t len;
      uint8_t kind;   /* RE_PROP_KIND_GC or RE_PROP_KIND_SCRIPT */
      uint8_t id;     /* index into re_prop_gc_masks, or the script */
    } re_prop_name;

  NAMES
  out.puts "static const char re_prop_name_chars[] ="
  chunk = 0
  while chunk < blob.length
    out.puts "  \"#{blob[chunk, 64]}\""
    chunk += 64
  end
  out.puts "  ;"
  out.puts
  out.puts "static const re_prop_name re_prop_names[] = {"
  entries.each do |name, off, kind, value, id|
    kindname = kind == :gc ? 'RE_PROP_KIND_GC' : 'RE_PROP_KIND_SCRIPT'
    out.puts "  { %5d, %3d, %s, %3d },  /* %s = %s */" % [off, name.length, kindname, id, name, value]
  end
  out.puts "};"
  out.puts
  out.puts "#define RE_PROP_NAME_COUNT (sizeof(re_prop_names) / sizeof(re_prop_names[0]))"
  out.puts
  out.puts "/* #{data.gc_runs.size} general category runs, #{data.script_runs.size} script runs, " \
           "#{data.categories.size} categories in #{mask_names.size} masks,"
  out.puts "   #{data.scripts.size} scripts, and #{entries.size} names in #{blob.length} bytes. */"
  out.puts
  out.puts "#endif /* MRB_RE_PROP_H */"
end

bytes = (data.gc_runs.size + data.script_runs.size) * 4
$stderr.puts "wrote #{File.join(outdir, 're_prop.h')}: #{data.gc_runs.size} + " \
             "#{data.script_runs.size} runs, #{bytes} bytes, #{entries.size} names"
