# Generate the characters the differential test asks about, from the Unicode
# Character Database.
#
#   ruby mrbgems/mruby-regexp/tools/difftest/gen_corpus.rb OUTDIR [UCDDIR]
#
# UCDDIR holds the files ucd.rb names and defaults to the copy it points at.
# Which characters are chosen, and why those, is tools/unicode/corpus_data.rb's
# to say; this file only writes the answer out.
#
# corpus.rb is Ruby that runs under CRuby and under mruby, since compare.rb
# puts it in front of probe.rb and hands the pair to each engine. It is
# committed, like the tables are, so that the two engines are asked about the
# same characters whether or not the database is on the machine.

require_relative '../../../../tools/unicode/corpus_data'

outdir = ARGV[0] or abort "usage: #{$0} OUTDIR [UCDDIR]"
data = Unicode::CorpusData.load(ARGV[1])

File.open(File.join(outdir, 'corpus.rb'), 'w') do |out|
  out.puts <<~HEAD
    # The characters the differential test asks about.
    #
    # Generated by mrbgems/mruby-regexp/tools/difftest/gen_corpus.rb from the
    # Unicode #{data.version} character database. Do not edit by hand.
    #
    # One character out of every class the engine's tables tell apart: every
    # general category, every script, each POSIX type and its complement, the
    # shapes case folding comes in, the widths the encoding changes at, and the
    # whole of ASCII. Each is the lowest codepoint in its class no newer than
    # Unicode #{Unicode::CorpusData::MAX_AGE}, which is the release the CRuby
    # the corpus is compared against carries, so that a character the two
    # databases disagree about cannot be read as an engine that does.
    #
    # The comment beside each is the class it stands for, and a codepoint
    # standing for more than one is named by the first that claimed it.
    #
    # See Copyright Notice in mruby.h

    CORPUS = [
  HEAD
  data.codepoints.each do |cp, why|
    out.puts "  0x%04X,  # %s" % [cp, why]
  end
  out.puts "]"
  out.puts
  out.puts "# #{data.codepoints.size} characters."
end

$stderr.puts "wrote #{File.join(outdir, 'corpus.rb')}: " \
             "#{data.codepoints.size} characters"
